/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedNutritionRouteImport } from './routes/_authed/nutrition'
import { Route as AuthedLogRouteImport } from './routes/_authed/log'
import { Route as AuthedHistoryRouteImport } from './routes/_authed/history'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'
import { Route as AuthedNutritionIndexRouteImport } from './routes/_authed/nutrition.index'
import { Route as AuthedLogIndexRouteImport } from './routes/_authed/log.index'
import { Route as AuthedHistoryIndexRouteImport } from './routes/_authed/history.index'
import { Route as AuthedLogWorkoutIdRouteImport } from './routes/_authed/log.$workoutId'
import { Route as AuthedHistoryWorkoutIdRouteImport } from './routes/_authed/history.$workoutId'
import { Route as AuthedNutritionRecipesIndexRouteImport } from './routes/_authed/nutrition.recipes.index'
import { Route as AuthedNutritionRecipesRecipeIdRouteImport } from './routes/_authed/nutrition.recipes.$recipeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNutritionRoute = AuthedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLogRoute = AuthedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHistoryRoute = AuthedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNutritionIndexRoute = AuthedNutritionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedNutritionRoute,
} as any)
const AuthedLogIndexRoute = AuthedLogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedLogRoute,
} as any)
const AuthedHistoryIndexRoute = AuthedHistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedHistoryRoute,
} as any)
const AuthedLogWorkoutIdRoute = AuthedLogWorkoutIdRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => AuthedLogRoute,
} as any)
const AuthedHistoryWorkoutIdRoute = AuthedHistoryWorkoutIdRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => AuthedHistoryRoute,
} as any)
const AuthedNutritionRecipesIndexRoute =
  AuthedNutritionRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthedNutritionRoute,
  } as any)
const AuthedNutritionRecipesRecipeIdRoute =
  AuthedNutritionRecipesRecipeIdRouteImport.update({
    id: '/recipes/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => AuthedNutritionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AuthedCalendarRoute
  '/history': typeof AuthedHistoryRouteWithChildren
  '/log': typeof AuthedLogRouteWithChildren
  '/nutrition': typeof AuthedNutritionRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/history/$workoutId': typeof AuthedHistoryWorkoutIdRoute
  '/log/$workoutId': typeof AuthedLogWorkoutIdRoute
  '/history/': typeof AuthedHistoryIndexRoute
  '/log/': typeof AuthedLogIndexRoute
  '/nutrition/': typeof AuthedNutritionIndexRoute
  '/nutrition/recipes/$recipeId': typeof AuthedNutritionRecipesRecipeIdRoute
  '/nutrition/recipes/': typeof AuthedNutritionRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendar': typeof AuthedCalendarRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/history/$workoutId': typeof AuthedHistoryWorkoutIdRoute
  '/log/$workoutId': typeof AuthedLogWorkoutIdRoute
  '/history': typeof AuthedHistoryIndexRoute
  '/log': typeof AuthedLogIndexRoute
  '/nutrition': typeof AuthedNutritionIndexRoute
  '/nutrition/recipes/$recipeId': typeof AuthedNutritionRecipesRecipeIdRoute
  '/nutrition/recipes': typeof AuthedNutritionRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/history': typeof AuthedHistoryRouteWithChildren
  '/_authed/log': typeof AuthedLogRouteWithChildren
  '/_authed/nutrition': typeof AuthedNutritionRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/history/$workoutId': typeof AuthedHistoryWorkoutIdRoute
  '/_authed/log/$workoutId': typeof AuthedLogWorkoutIdRoute
  '/_authed/history/': typeof AuthedHistoryIndexRoute
  '/_authed/log/': typeof AuthedLogIndexRoute
  '/_authed/nutrition/': typeof AuthedNutritionIndexRoute
  '/_authed/nutrition/recipes/$recipeId': typeof AuthedNutritionRecipesRecipeIdRoute
  '/_authed/nutrition/recipes/': typeof AuthedNutritionRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/history'
    | '/log'
    | '/nutrition'
    | '/settings'
    | '/history/$workoutId'
    | '/log/$workoutId'
    | '/history/'
    | '/log/'
    | '/nutrition/'
    | '/nutrition/recipes/$recipeId'
    | '/nutrition/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendar'
    | '/settings'
    | '/'
    | '/history/$workoutId'
    | '/log/$workoutId'
    | '/history'
    | '/log'
    | '/nutrition'
    | '/nutrition/recipes/$recipeId'
    | '/nutrition/recipes'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/calendar'
    | '/_authed/history'
    | '/_authed/log'
    | '/_authed/nutrition'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/history/$workoutId'
    | '/_authed/log/$workoutId'
    | '/_authed/history/'
    | '/_authed/log/'
    | '/_authed/nutrition/'
    | '/_authed/nutrition/recipes/$recipeId'
    | '/_authed/nutrition/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nutrition': {
      id: '/_authed/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthedNutritionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/log': {
      id: '/_authed/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthedLogRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/history': {
      id: '/_authed/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthedHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nutrition/': {
      id: '/_authed/nutrition/'
      path: '/'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof AuthedNutritionIndexRouteImport
      parentRoute: typeof AuthedNutritionRoute
    }
    '/_authed/log/': {
      id: '/_authed/log/'
      path: '/'
      fullPath: '/log/'
      preLoaderRoute: typeof AuthedLogIndexRouteImport
      parentRoute: typeof AuthedLogRoute
    }
    '/_authed/history/': {
      id: '/_authed/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthedHistoryIndexRouteImport
      parentRoute: typeof AuthedHistoryRoute
    }
    '/_authed/log/$workoutId': {
      id: '/_authed/log/$workoutId'
      path: '/$workoutId'
      fullPath: '/log/$workoutId'
      preLoaderRoute: typeof AuthedLogWorkoutIdRouteImport
      parentRoute: typeof AuthedLogRoute
    }
    '/_authed/history/$workoutId': {
      id: '/_authed/history/$workoutId'
      path: '/$workoutId'
      fullPath: '/history/$workoutId'
      preLoaderRoute: typeof AuthedHistoryWorkoutIdRouteImport
      parentRoute: typeof AuthedHistoryRoute
    }
    '/_authed/nutrition/recipes/': {
      id: '/_authed/nutrition/recipes/'
      path: '/recipes'
      fullPath: '/nutrition/recipes/'
      preLoaderRoute: typeof AuthedNutritionRecipesIndexRouteImport
      parentRoute: typeof AuthedNutritionRoute
    }
    '/_authed/nutrition/recipes/$recipeId': {
      id: '/_authed/nutrition/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/nutrition/recipes/$recipeId'
      preLoaderRoute: typeof AuthedNutritionRecipesRecipeIdRouteImport
      parentRoute: typeof AuthedNutritionRoute
    }
  }
}

interface AuthedHistoryRouteChildren {
  AuthedHistoryWorkoutIdRoute: typeof AuthedHistoryWorkoutIdRoute
  AuthedHistoryIndexRoute: typeof AuthedHistoryIndexRoute
}

const AuthedHistoryRouteChildren: AuthedHistoryRouteChildren = {
  AuthedHistoryWorkoutIdRoute: AuthedHistoryWorkoutIdRoute,
  AuthedHistoryIndexRoute: AuthedHistoryIndexRoute,
}

const AuthedHistoryRouteWithChildren = AuthedHistoryRoute._addFileChildren(
  AuthedHistoryRouteChildren,
)

interface AuthedLogRouteChildren {
  AuthedLogWorkoutIdRoute: typeof AuthedLogWorkoutIdRoute
  AuthedLogIndexRoute: typeof AuthedLogIndexRoute
}

const AuthedLogRouteChildren: AuthedLogRouteChildren = {
  AuthedLogWorkoutIdRoute: AuthedLogWorkoutIdRoute,
  AuthedLogIndexRoute: AuthedLogIndexRoute,
}

const AuthedLogRouteWithChildren = AuthedLogRoute._addFileChildren(
  AuthedLogRouteChildren,
)

interface AuthedNutritionRouteChildren {
  AuthedNutritionIndexRoute: typeof AuthedNutritionIndexRoute
  AuthedNutritionRecipesRecipeIdRoute: typeof AuthedNutritionRecipesRecipeIdRoute
  AuthedNutritionRecipesIndexRoute: typeof AuthedNutritionRecipesIndexRoute
}

const AuthedNutritionRouteChildren: AuthedNutritionRouteChildren = {
  AuthedNutritionIndexRoute: AuthedNutritionIndexRoute,
  AuthedNutritionRecipesRecipeIdRoute: AuthedNutritionRecipesRecipeIdRoute,
  AuthedNutritionRecipesIndexRoute: AuthedNutritionRecipesIndexRoute,
}

const AuthedNutritionRouteWithChildren = AuthedNutritionRoute._addFileChildren(
  AuthedNutritionRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedHistoryRoute: typeof AuthedHistoryRouteWithChildren
  AuthedLogRoute: typeof AuthedLogRouteWithChildren
  AuthedNutritionRoute: typeof AuthedNutritionRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedHistoryRoute: AuthedHistoryRouteWithChildren,
  AuthedLogRoute: AuthedLogRouteWithChildren,
  AuthedNutritionRoute: AuthedNutritionRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
